---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: chef/centos-6.5
    driver_config:
      network:
      - ['forwarded_port', {guest: 4440, host: 4440, auto_correct: true}] # rundeck server port
      - ['forwarded_port', {guest: 9980, host: 9980, auto_correct: true}] # chef-rundeck port

suites:
  - name: server
    run_list:
      - recipe[rundeck-server]
