#
# This uses https://rubygems.org/gems/kitchen-docker
#
---
driver:
  name: docker

driver_config:
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: server
    run_list:
      - recipe[rundeck-server]

  - name: job
    attributes:
      rundeck_server:
        rundeck-config.framework:
          rundeck.tokens.file: '/etc/rundeck/token.properties'
    run_list:
      - recipe[rundeck-test]
